spring:
  application:
    name: BankSystemCustomers

  datasource:
    url: jdbc:mysql://82.156.214.214/DBBS
    username: 12938475601
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082