spring:
  application:
    name: BankSystemCustomers

  datasource:
    url: jdbc:mysql://82.156.214.214/DBBS
    username: 12938475601
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082

app:
  # 备份配置
  backup:
    # 备份数据库
    db: "DBBS"
    # 备份文件存储目录
    dir: "D:\\backupDatabase"
    # 备份文件最多保留时间。如，5分钟：5m、12小时：12h、1天：1d
    max-age: 1d